Added list feature, prompting for full file name with extension instead of just name

diff --git a/cooler b/cooler
--- a/cooler
+++ b/cooler
@@ -53,41 +53,47 @@ EXECDIR="$(pwd)"
 if [ "$1" = "export" ]
 	then
 	echo -e "Creating working directory..."
-	rm -rf "$2" >/dev/null ; mkdir "$2"
-	pushd "$2" >/dev/null 2>&1
+	echo "${2%.*}"
+	rm -rf "${2%.*}" >/dev/null ; mkdir "${2%.*}"
+	echo "$(pwd)"
+	pushd "${2%.*}" >/dev/null 2>&1
+	echo "$(pwd)"
 	if [ ! "$3" = "--no-brew" ]
 		then
 		echo -e "Reading configured taps..."
-		brew tap > "$2/tap.cr"
+		brew tap > "tap.cr"
 		echo -e "Reading installed formulae..."
-		brew list | tr "  " "\n" > "$2/brew.cr"
+		brew list | tr "  " "\n" > "brew.cr"
 	fi
 	if [ ! "$3" = "--no-cask" -a ! "$3" = "--no-brew" ]
 		then
 		echo -e "Reading installed casks..."
-		brew cask list | tr "  " "\n" > "$2/cask.cr"
+		brew cask list | tr "  " "\n" > "cask.cr"
 	fi
 	if [ ! "$3" = "--no-port" ]
 		then
 		echo -e "Reading installed ports..."
-		port list installed | awk '{ print $1 }' > "$2/port.cr"
+		port list installed | awk '{ print $1 }' > "port.cr"
 	fi
 	cd ..
-	tar czf "$(basename $2).cb" "$(basename $2)" >/dev/null 2>&1
-	echo -e "\033[1;32mYour Cooler bundle is at\033[1;33m $(pwd)/$(basename $2).cb\033[1;34m.\033[22;0m"
+	echo "$(pwd)"
+	echo "tar czvf "$(basename "$2")" "$(basename "${2%.*}")""
+	tar czvf "./$(basename "$2")" "$(basename "${2%.*}")"
+	echo -e "\033[1;32mYour Cooler bundle is at\033[1;33m $2\033[1;34m.\033[22;0m"
 	popd >/dev/null 2>&1
-	rm -rf "$2" >/dev/null 2>&1
+	echo "$(pwd)"
+	rm -rf "${2%.*}" >/dev/null 2>&1
 	exit 0;
 elif [ "$1" = "import" ]
 	then
-	if [ -e "$2.cb" -o -e "$(dirname "$2")/$(basename $2).cb)" ]
+	if [ -e "$2" -o -e "$(dirname "${2%.*}")/$2).cb)" ]
 		then
-			pushd "$(dirname "$2")" >/dev/null 2>&1
-			ARCDIR="$2"
-			tar xzf "$2.cb"
-			if [ -s "$2/brew.cr" -a ! "$3" = "--no-brew" ]
+			pushd "$(dirname "${2%.*}")" >/dev/null 2>&1
+			ARCDIR="${2%.*}"
+			tar xzf "$2"
+			if [ -s "${2%.*}/brew.cr" -a ! "$3" = "--no-brew" ]
 				then
-				[ -s "$2/brew.cr" ] && (( command -v brew >/dev/null 2>&1 && echo -e "\r\033[K[ \033[1;34mINSTALLING\033[22;0m ] Installing dependency: Homebrew" ) || (rm -rf /usr/local/Cellar /usr/local/.git ; brew cleanup >/dev/null 2>&1; yes | ruby -e "$(curl -fsSL https://raw.github.com/alebcay/cooler/master/installbrew)" >/dev/null 2>&1))
+				[ -s "${2%.*}/brew.cr" ] && (( command -v brew >/dev/null 2>&1 && echo -e "\r\033[K[ \033[1;34mINSTALLING\033[22;0m ] Installing dependency: Homebrew" ) || (rm -rf /usr/local/Cellar /usr/local/.git ; brew cleanup >/dev/null 2>&1; yes | ruby -e "$(curl -fsSL https://raw.github.com/alebcay/cooler/master/installbrew)" >/dev/null 2>&1))
 				if [ "$?" == 0 ]
 					then
 					echo -e "\r\033[K[ \033[1;32mDONE\033[22;0m ] Installing dependency: Homebrew"
@@ -101,12 +107,12 @@ elif [ "$1" = "import" ]
 				importTaps
 				importBrews
 			fi
-			if [ -s "$2/cask.cr" -a ! "$3" = "--no-cask" -a ! "$3" = "--no-brew" ]
+			if [ -s "${2%.*}/cask.cr" -a ! "$3" = "--no-cask" -a ! "$3" = "--no-brew" ]
 				then
-				[ -s "$2/cask.cr" ] && ( echo -ne "[ \033[1;33mINSTALLING\033[22;0m ] Installing dependency: Homebrew-Cask" && ( brew install phinze/cask/brew-cask >/dev/null 2>&1 && echo -e "\r\033[K[ \033[1;32mDONE\033[22;0m ] Installing dependency: Homebrew-Cask" ) || echo -e "\r\033[K[ \033[1;31mFAILED\033[22;0m ] Installing dependency: Homebrew-Cask")
+				[ -s "${2%.*}/cask.cr" ] && ( echo -ne "[ \033[1;33mINSTALLING\033[22;0m ] Installing dependency: Homebrew-Cask" && ( brew install phinze/cask/brew-cask >/dev/null 2>&1 && echo -e "\r\033[K[ \033[1;32mDONE\033[22;0m ] Installing dependency: Homebrew-Cask" ) || echo -e "\r\033[K[ \033[1;31mFAILED\033[22;0m ] Installing dependency: Homebrew-Cask")
 				importCasks
 			fi
-			if [ -s "$2/port.cr" -a ! "$3" = "--no-port" ]
+			if [ -s "${2%.*}/port.cr" -a ! "$3" = "--no-port" ]
 				then
 				if [[ "$EUID" != 0 ]]; then
 				    echo "Administrator privileges are required to install MacPorts packages:"
@@ -124,8 +130,51 @@ elif [ "$1" = "update" ]
 	echo -e "\033[1;32mCooler is now up to date.\033[22;0m"
 elif [ "$1" = "importPorts" ]
 	then
-	ARCDIR="$2"
+	ARCDIR="${2%.*}"
 	importPorts
+elif [ "$1" = "list" ]
+	then
+	if [ -e "$2" -o -e "$(dirname "${2%.*}")/$2" ]
+		then
+			pushd "$(dirname "${2%.*}")" >/dev/null 2>&1
+			ARCDIR="${2%.*}"
+			tar xzf "$2"
+			echo -e "\033[1;34mContents of cooler.resource.brew: \033[22;0m"
+			if [ -s "${2%.*}/brew.cr" ]
+				then
+				while read p; do
+					echo "$p"
+				done < "$ARCDIR/brew.cr"
+			fi
+			echo ""
+			echo -e "\033[1;34mContents of cooler.resource.tap: \033[22;0m"
+			if [ -s "${2%.*}/tap.cr" ]
+				then
+				while read p; do
+					echo "$p"
+				done < "$ARCDIR/tap.cr"
+			fi
+			echo ""
+			echo -e "\033[1;34mContents of cooler.resource.cask: \033[22;0m"
+			if [ -s "${2%.*}/cask.cr" ]
+				then
+				while read p; do
+					echo "$p"
+				done < "$ARCDIR/cask.cr"
+			fi
+			echo ""
+			echo -e "\033[1;34mContents of cooler.resource.port: \033[22;0m"
+			if [ -s "${2%.*}/port.cr" ]
+				then
+					while read p; do
+						echo "$p"
+					done < "$ARCDIR/port.cr"
+			fi
+			popd >/dev/null 2>&1
+			rm -rf "$ARCDIR"
+	else
+		echo -e "[ \033[1;31mFAILED\033[22;0m ] No such bundle: $2" && exit 1
+	fi
 else
 	echo "cooler - homebrew/homebrew-cask package migration and transport"
 	echo "usage: cooler [import/export] coolerBundleName <flags>"
